"use client";

import { ArrowUpRight, BookOpen, Check, Clock3, Code2, Headphones, MapPin, MessageCircle, Plug, ShieldCheck, ShoppingBag, Sparkles, Star, TrendingUp, Users, Workflow } from "lucide-react";
import { useState } from "react";
import { demoActions, useDemo } from "@/lib/demo-store";
import { currency, products } from "@/lib/demo-data";
import { FoodArt } from "./ui";
import { ConciergeOverview } from "./concierge";
import { CsatDashboard } from "./csat";
import catalog from "@/lib/catalog.json";

export function WorkspaceView({ view, onDemo, attention }: { view: "metrics" | "automation" | "knowledge"; onDemo: () => void; attention?: React.ReactNode }) {
  const state = useDemo();
  const [tab, setTab] = useState("Pinheiros");
  const titles = { metrics: ["Cada conversa conta", "Um olhar sobre o piloto. E sobre as pessoas por trás dos números."], automation: ["Inteligência com cuidado", "A assistente resolve o simples. Sua equipe cuida do que importa."], knowledge: ["A informação certa, sempre", "Uma fonte de verdade para um atendimento consistente em cada unidade."] };
  const orders = state.conversations.filter((c) => c.order?.confirmed);

  return <div className="workspace-view"><div className="view-title"><span className="heading-eyebrow"><span className="live-dot" /> SABOR EXPRESS · PILOTO CONTROLADO</span><h1>{titles[view][0]}<span>.</span></h1><p>{titles[view][1]}</p></div>
    {view === "metrics" && <>
      {attention}
      <CsatDashboard />
      <div className="metrics-banner"><div><span className="pill-light">PLANO DE 60 DIAS</span><h2>Confiança se constrói.<br />Resultado se mede.</h2><p>3 unidades no piloto. Expansão condicionada<br />à qualidade, à adoção e ao valor comprovado.</p><button onClick={onDemo}>Explorar a demonstração <ArrowUpRight size={15} /></button></div><div className="banner-orbit"><TrendingUp size={72} strokeWidth={1} /><span>42<span>unidades no horizonte</span></span></div></div>
      <div className="section-title"><h2>O que vamos medir</h2><span>Metas propostas · sujeitas à baseline</span></div><div className="kpi-grid">{[
        { icon: <Clock3 />, label: "Primeira resposta", value: "< 30s", desc: "P90 entre a mensagem recebida e a primeira resposta útil. Separar IA e humano.", tag: "Eficiência" },
        { icon: <Sparkles />, label: "Resolução com IA", value: "≥ 60%", desc: "Conversas elegíveis resolvidas sem humano e sem reabertura em 24 horas.", tag: "Eficiência" },
        { icon: <Star />, label: "Satisfação do cliente", value: "≥ 4,5/5", desc: "CSAT no encerramento. Acompanhar também taxa de resposta e reclamações.", tag: "Experiência" },
        { icon: <ShoppingBag />, label: "Conversão em pedido", value: "+ 10%", desc: "Uplift relativo contra lojas-controle: pedidos confirmados / conversas com intenção de compra.", tag: "Negócio" },
        { icon: <Users />, label: "Adoção da equipe", value: "≥ 85%", desc: "Atendentes ativos na semana / atendentes treinados nas unidades do piloto.", tag: "Adoção" },
        { icon: <Headphones />, label: "Transferência atendida", value: "< 5min", desc: "P90 até aceite humano no horário de operação, sem perder o contexto.", tag: "Qualidade" },
      ].map((k) => <div className="kpi-card" key={k.label}><div><span>{k.icon}</span><small>{k.tag}</small></div><h3>{k.label}</h3><strong>{k.value}</strong><p>{k.desc}</p></div>)}</div>
      <div className="section-title"><h2>O que aconteceu nesta demonstração</h2><span>Estado real deste navegador</span></div><div className="session-metrics"><div><MessageCircle size={20} /><strong>{state.conversations.length}</strong><span>Conversas no workspace</span></div><div><ShoppingBag size={20} /><strong>{orders.length}</strong><span>Pedidos simulados confirmados</span></div><div><TrendingUp size={20} /><strong>{currency(orders.reduce((sum, c) => sum + (c.order?.price || 0), 0))}</strong><span>Valor dos pedidos simulados</span></div></div>
      <div className="section-title"><h2>Do kickoff ao impacto</h2><span>60 dias após a aprovação</span></div><div className="timeline">{[["01–10", "Ouvir e mapear", "Baseline, 3 lojas representativas e alinhamento com franqueados."], ["11–25", "Conectar e validar", "APIs em sandbox, conhecimento aprovado e teste com atendentes."], ["26–40", "Aprender no piloto", "Operação assistida, revisão diária e comparação com lojas-controle."], ["41–60", "Expandir com critério", "Ondas de 10, 15 e 14 lojas, conforme capacidade e metas."]].map(([days, title, desc], i) => <div key={title}><span>FASE 0{i + 1}</span><strong>{title}</strong><small>Dias {days}</small><p>{desc}</p></div>)}</div><div className="info-callout">Antes da aprovação: diagnóstico, premissas e proposta ao conselho em até 3 semanas. As metas são hipóteses para validação; os números do cabeçalho do inbox são ilustrativos e não representam resultados obtidos.</div>
    </>}
    {view === "automation" && <>
      <div className="agent-overview"><div className="large-ai-icon"><Sparkles size={30} /></div><div><h2>Uma recepção. Vários especialistas.</h2><p>Seu primeiro atendimento. Com contexto, clareza e uma saída humana.</p><span className="model-label">Automação controlada por conversa</span></div><div className="agent-switch"><span>{state.automation ? "Assistente ativa" : "Assistente pausada"}</span><button role="switch" aria-checked={state.automation} aria-label="Ativar assistente" className={`toggle ${state.automation ? "on" : ""}`} onClick={demoActions.toggleAutomation}><span /></button></div></div>
      <ConciergeOverview />
      <div className="automation-columns"><section className="rules-card"><h2><ShieldCheck size={19} />Regras de um bom atendimento</h2>{[["Cardápio, preço e estoque", "Valores e quantidades obtidos dos sistemas fictícios.", true], ["Pedidos e reservas com consentimento", "O resumo atual precisa ser confirmado pelo cliente.", true], ["Reclamações e pedidos de uma pessoa", "Transferência imediata, preservando a conversa.", false], ["Alergias, grupos grandes e exceções", "A equipe cuida dos casos fora das regras da demo.", false]].map(([title, desc, automatic]) => <div className="rule-row" key={String(title)}><span className={automatic ? "rule-auto" : "rule-human"}>{automatic ? <Check size={15} /> : <Headphones size={15} />}</span><span><strong>{title}</strong><small>{desc}</small></span><span className="rule-badge">{automatic ? "Sistema" : "Equipe"}</span></div>)}</section><section className="rules-card"><h2><Plug size={19} />Conexões do projeto</h2>{[["WhatsApp Business", "Interface demonstrativa de mensagens."], ["RD Station", "Próxima integração: contato, intenção e resultado."], ["Pedidos, estoque e agenda", "Sistemas fictícios funcionais, persistidos em SQLite."]].map(([title, desc]) => <div className="integration-row" key={title}><div><strong>{title}</strong><p>{desc}</p></div><span>Simulada</span></div>)}<div className="integration-next"><Code2 size={17} /><span>Decisões verificáveis<strong>O modelo propõe a ação. O sistema confere contexto, preço, capacidade e consentimento antes de gravar.</strong></span></div></section></div>
      <div className="n8n-card"><Workflow size={31} /><div><span className="section-kicker">AUTOMAÇÃO PROPOSTA · N8N</span><h3>O atendimento termina. O aprendizado continua.</h3><p>Webhook → deduplicar evento → classificar intenção → atualizar o contato no RD Station → registrar KPI → alertar a equipe se o SLA estiver próximo do limite.</p></div><span className="model-label">Desenho para a próxima fase</span></div>
    </>}
    {view === "knowledge" && <>
      <div className="knowledge-banner"><BookOpen size={28} /><div><h2>Conhecimento local. Padrão de rede.</h2><p>Informações de demonstração. Em produção, cada franqueado valida os dados da sua unidade.</p></div><span className="model-label">Base demonstrativa</span></div>
      <div className="knowledge-tabs">{["Pinheiros", "Vila Mariana", "Moema"].map((store) => <button className={tab === store ? "active" : ""} key={store} onClick={() => setTab(store)}><MapPin size={14} />{store}</button>)}</div>
      <div className="knowledge-grid"><section className="knowledge-card"><span className="section-kicker">INFORMAÇÕES DA UNIDADE</span><h2>Sabor Express {tab}</h2><div><Clock3 size={18} /><span><strong>Horário de funcionamento</strong><p>Todos os dias, das 11h às 23h.</p></span></div><div><MapPin size={18} /><span><strong>Estacionamento</strong><p>{tab === "Pinheiros" ? "Conveniado ao lado. Primeira hora gratuita para clientes." : "Informação não cadastrada. Encaminhar para a equipe."}</p></span></div>
        <div><ShoppingBag size={18} /><span><strong>Pedidos na demonstração</strong><p>Retirada sem frete: {catalog.fulfillment.pickupEstimate}. Entrega: {catalog.fulfillment.deliveryEstimate}, com frete fictício de {currency(catalog.stores.find((s) => s.name.endsWith(tab))?.deliveryFee || 0)}. Pagamento no recebimento, sem cobrança real.</p></span></div>
        <div><ShieldCheck size={18} /><span><strong>Restrições alimentares</strong><p>Sempre confirmar ingredientes e contaminação cruzada com a equipe da loja.</p></span></div></section><section className="knowledge-card"><span className="section-kicker">TOM DE VOZ</span><h2>Próximo. Claro. De verdade.</h2><blockquote>“Oi! Que bom te ver por aqui 💚<br />Como posso deixar seu dia mais gostoso?”</blockquote><ul className="voice-list"><li><Check size={14} />Apresentar-se como assistente virtual.</li><li><Check size={14} />Falar como gente, sem menus intermináveis.</li><li><Check size={14} />Não prometer o que a loja não confirmou.</li><li><Check size={14} />Facilitar o acesso ao atendimento humano.</li></ul></section></div>
      <div className="section-title"><h2>Cardápio da demonstração</h2><span>Preços fictícios · iguais nas 3 lojas do piloto</span></div><div className="knowledge-menu">{products.map((p) => <article key={p.id}><div className={p.color}><FoodArt variant={p.id} /></div><section><h3>{p.name}</h3><p>{p.description}</p><strong>{currency(p.price)}</strong></section></article>)}</div>
    </>}
  </div>;
}
